### ISSUE TITLE
vizAPOTC  ：change idents does not take effect

### ISSUE THREAD

**Issue by Maojie6509** [Qile0317/scballpack#7]
When I set the idents of a Seurat object to the annotated cell types, but the visualization results in vizAPOTC still show colors based on clusters, even though I modified idents, it does not take effect.
![image](https://github.com/Qile0317/APackOfTheClones/assets/9159535/4755754c-5656-44ec-b6da-89077baf3d00)

**Comment by Qile0317** [comment]
Hi, thanks for using the package! I was actually just in the process of implementing the feature so that you can identify clusters based on any ident, as I just realized this issue too a few days ago - it was something I completely overlooked when making the package. I will have a new version that implements this feature up within a few days.

**Comment by Qile0317** [comment]
A new CRAN release 1.2.0 is now up - please check `NEWS.md` for the changes. Most notably, clonotypes are grouped into clusters by the current active ident by default now which should have solved your issue - please open a new github issue if there are any bugs.
